import {
  // create naive ui
  create,
  // component
  NButton,
  NSpace,
  NGrid,
  NGridItem,
  NLayout,
  NLayoutHeader,
  NLayoutContent,
  NLayoutFooter,
  NLayoutSider,
  NMenu,
  NIcon,
  NAvatar,
  NDropdown,
  NForm,
  NInput,
  NAutoComplete,
  NCascader,
  NColorPicker,
  NCheckbox,
  NCheckboxGroup,
  NDatePicker,
  NDynamicInput,
  NDynamicTags,
  NInputNumber,
  NRadio,
  NRadioGroup,
  NButtonGroup,
  NRate,
  NSelect,
  NSlider,
  NSwitch,
  NTimePicker,
  NTreeSelect,
  NUpload,
} from "naive-ui";
// 通用字体
import "vfonts/Lato.css";
// 等宽字体
import "vfonts/FiraCode.css";

const naive = create({
  components: [
    NButton,
    NSpace,
    NGrid,
    NGridItem,
    NLayout,
    NLayoutHeader,
    NLayoutContent,
    NLayoutFooter,
    NLayoutSider,
    NMenu,
    NIcon,
    NAvatar,
    NDropdown,
    NForm,
    NInput,
    NInputNumber,
    NRadio,
    NRadioGroup,
    NButtonGroup,
    NRate,
    NSelect,
    NSlider,
    NSwitch,
    NTimePicker,
    NTreeSelect,
    NUpload,
    NAutoComplete,
    NCascader,
    NColorPicker,
    NCheckbox,
    NCheckboxGroup,
    NDatePicker,
    NDynamicInput,
    NDynamicTags,
  ],
});
export default naive;
